import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { OrganizationStoreProvider } from "@/zustand/providers/organization-store-provider";
import { IntegrationsStoreProvider } from "@/zustand/providers/integrations-store-provider";
import { DashboardStoreProvider } from "@/zustand/providers/dashboard-store-provider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Founders' Stack",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider>
					<OrganizationStoreProvider>
						<IntegrationsStoreProvider>
							<DashboardStoreProvider>
								{children}
							</DashboardStoreProvider>
						</IntegrationsStoreProvider>
					</OrganizationStoreProvider>
					<Toaster />
				</ThemeProvider>
			</body>
		</html>
	);
}
